### ISSUE TITLE
Error Input file contains unsupported image format

### ISSUE THREAD

**Issue by SMART-Seraph** [ZachHappel/qr-with-logo#9]
Hi I'm getting "Error Input file contains unsupported image format" despite (as far as I can tell) setting everything up correctly. Here's the full output:

This is saveas_file_name: public/img/qrCodes/Fancy-Tournament-2022.png
saveas_file_name instanceof String: true
All PNG parameters
Made new QR
Saving QR as: init_non_logo_qr.png
Output: PNG
SaveAs: public/img/qrCodes/Fancy-Tournament-2022.png
Error Input file contains unsupported image format

Based on this code:

```
async function generateQRcode(event, next) {
  const data = `${event.slug}`;
  QRLogo.generateQRWithLogo(
    data,
    "public/img/logo.png",
    {
      color: {
        dark: "#98191e", // Red dots
        light: "#FFFFFF", // Transparent background
      },
    },
    "PNG",
    `public/img/qrCodes/${event.slug}.png`,
    function (err) {
      if (err) {
        next(new AppError("There was an error creating your QR code.", 400));
      } else {
      }
    }
  );
}
```

**Comment by SMART-Seraph** [comment]
Also just FYI having this module installed was blocking me from uploading to Heroku via Git. Something to do with Sharp (I think maybe it's trying to overwrite the version of Sharp I already have? Not sure).

**Comment by ZachHappel** [comment]
https://github.com/ZachHappel/qr-with-logo/commit/01b6055f2c2974329c358482ff6afb0a4093458a
Updated Sharp version, which should fix this. Let me know if you are still having any issues.
